# We use Cirrus CI to test on FreeBSD.
# For GNU/Linix CI see GitHub Actions.

freebsd_instance:
  image_family: freebsd-13-0

main_freebsd_task:
  name: Main (FreeBSD)
  script:
    - pkg install --yes autoconf automake
    - ./autogen.sh
    - ./configure --enable-tests CFLAGS='-O3 -fPIC'
    - make
    - make check
    - sudo make install

ruby_freebsd_task:
  name: Ruby (FreeBSD)
  dependencies_script:
    - pkg install --yes autoconf automake git wget
  ruby_cache:
    fingerprint_key: ruby-3.0.3-fix
    folder: ruby-3.0.3
    populate_script:
      - wget https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.3.tar.gz
      - tar -xzf ruby-3.0.3.tar.gz
      - cd ruby-3.0.3
      - ./configure
      - make
      - cd ..
  upload_caches: [ruby]
  script:
    - cd ruby-3.0.3
    - sudo make install
    - cd ..
    - ./autogen.sh
    - ./configure CFLAGS='-O3 -fPIC'
    - make
    - sudo make install
    - cd pkgs/ruby
    - bundle install
    - bundle exec rake compile
    - bundle exec rake
