# We use Cirrus CI to test on FreeBSD.
# For GNU/Linix CI see GitHub Actions.

freebsd_instance:
  image_family: freebsd-13-0

task:
  script:
    - pkg install --yes autoconf automake
    - ./autogen.sh
    - ./configure --enable-tests CFLAGS='-O3 -fPIC'
    - make
    - make check
    - sudo make install

ruby_task:
  script:
    - pkg install --yes autoconf automake git ruby rubygem-bundler rubygem-rake
    - ./autogen.sh
    - ./configure CFLAGS='-O3 -fPIC'
    - make
    - sudo make install
    - cd pkgs/ruby
    - bundle install
    - rake compile
    - rake
