# We use Cirrus CI to test on FreeBSD.
# For GNU/Linix CI see GitHub Actions.

freebsd_instance:
  image_family: freebsd-13-0

task:
  script:
    - pkg install --yes autoconf automake
    - ./autogen.sh
    - ./configure --enable-tests CFLAGS='-O3 -fPIC'
    - make
    - make check
    - sudo make install

ruby_task:
  dependencies_script:
    - pkg install --yes autoconf automake git
  ruby_cache:
    folder: ruby-3.0.3
    populate_script:
      - wget https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.3.tar.gz
      - tar -xzf ruby-3.0.3.tar.gz
      - cd ruby-3.0.3
      - ./configure
      - make
      - cd ..
  script:
    - ./autogen.sh
    - ./configure CFLAGS='-O3 -fPIC'
    - make
    - sudo make install
    - cd pkgs/ruby
    - bundle install
    - bundle exec rake compile
    - bundle exec rake
