name: Ruby

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: ['', '--without-all']
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: dependencies
        run: sudo apt-get --yes install cppcheck
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: ./configure ${{matrix.packages}} CFLAGS='-O3'
      - name: make
        run: make
      - name: install
        run: sudo make install
      - working-directory: bindings/ruby
        name: setup
        run: ./bin/setup
      - working-directory: bindings/ruby
        name: compile
        run: rake compile
      - working-directory: bindings/ruby
        name: test & lint
        run: rake
      - working-directory: bindings/ruby
        name: cppcheck
        run: cppcheck --quiet --error-exitcode=1 --std=c99 --enable=warning,style,performance,portability .
