name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_deny_warnings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: ./configure --enable-assert --disable-multiboot2 CFLAGS='-Werror'
      - name: make
        run: make
      - name: check
        run: make check

  test_allow_warnings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: ./configure --enable-assert
      - name: make
        run: make
      - name: check
        run: make check
